//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UILanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UILanguage.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account list.
        /// </summary>
        public static string AccountList {
            get {
                return ResourceManager.GetString("AccountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user failed.
        /// </summary>
        public static string AddAccountFailed {
            get {
                return ResourceManager.GetString("AddAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user successfully.
        /// </summary>
        public static string AddAccountSuccess {
            get {
                return ResourceManager.GetString("AddAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced printer settings.
        /// </summary>
        public static string AdvancedPrinterSettings {
            get {
                return ResourceManager.GetString("AdvancedPrinterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After production.
        /// </summary>
        public static string AfterProduction {
            get {
                return ResourceManager.GetString("AfterProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is already running!.
        /// </summary>
        public static string ApplicationIsAlreadyRunning {
            get {
                return ResourceManager.GetString("ApplicationIsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete file?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteFile {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete user .
        /// </summary>
        public static string AreYouSureYouWantToDeleteUser {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto load file.
        /// </summary>
        public static string AutoLoad {
            get {
                return ResourceManager.GetString("AutoLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto reconnect.
        /// </summary>
        public static string AutoReconnect {
            get {
                return ResourceManager.GetString("AutoReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera disconected.
        /// </summary>
        public static string CameraDisconnected {
            get {
                return ResourceManager.GetString("CameraDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera settings.
        /// </summary>
        public static string CameraSettings {
            get {
                return ResourceManager.GetString("CameraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string CameraTMP {
            get {
                return ResourceManager.GetString("CameraTMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process cannot access the file.
        /// </summary>
        public static string CannotAccessFile {
            get {
                return ResourceManager.GetString("CannotAccessFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not access to file.
        /// </summary>
        public static string CannotAccessToFile {
            get {
                return ResourceManager.GetString("CannotAccessToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t detect.
        /// </summary>
        public static string CannotDetect {
            get {
                return ResourceManager.GetString("CannotDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification result backup file not found.
        /// </summary>
        public static string CanNotFindCheckedResult {
            get {
                return ResourceManager.GetString("CanNotFindCheckedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database file not found.
        /// </summary>
        public static string CanNotFindDatabase {
            get {
                return ResourceManager.GetString("CanNotFindDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed response backup file not found.
        /// </summary>
        public static string CanNotFindPrintedResponse {
            get {
                return ResourceManager.GetString("CanNotFindPrintedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can read.
        /// </summary>
        public static string CanRead {
            get {
                return ResourceManager.GetString("CanRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t detect.
        /// </summary>
        public static string CantDetect {
            get {
                return ResourceManager.GetString("CantDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check all printer settings.
        /// </summary>
        public static string CheckAllPrinterSettings {
            get {
                return ResourceManager.GetString("CheckAllPrinterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string CheckedFailed {
            get {
                return ResourceManager.GetString("CheckedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string CheckedPassed {
            get {
                return ResourceManager.GetString("CheckedPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification results.
        /// </summary>
        public static string CheckedResult {
            get {
                return ResourceManager.GetString("CheckedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job logs.
        /// </summary>
        public static string CheckedResult1 {
            get {
                return ResourceManager.GetString("CheckedResult1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template print does not exist, please check the template print list again or connect the printer!.
        /// </summary>
        public static string CheckExistTemplatePrinter {
            get {
                return ResourceManager.GetString("CheckExistTemplatePrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear log.
        /// </summary>
        public static string ClearLog {
            get {
                return ResourceManager.GetString("ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear response.
        /// </summary>
        public static string ClearResponse {
            get {
                return ResourceManager.GetString("ClearResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare type.
        /// </summary>
        public static string CompareType {
            get {
                return ResourceManager.GetString("CompareType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the barcode verification process!.
        /// </summary>
        public static string CompleteTheBarcodeVerificationProcess {
            get {
                return ResourceManager.GetString("CompleteTheBarcodeVerificationProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the license for this software, please contact the vendor!.
        /// </summary>
        public static string ConfirmPC {
            get {
                return ResourceManager.GetString("ConfirmPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new job.
        /// </summary>
        public static string CreateANewJob {
            get {
                return ResourceManager.GetString("CreateANewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database does not exist.
        /// </summary>
        public static string DatabaseDoesNotExist {
            get {
                return ResourceManager.GetString("DatabaseDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string DatabaseFrmMain {
            get {
                return ResourceManager.GetString("DatabaseFrmMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data checked file name.
        /// </summary>
        public static string DataCheckedFileName {
            get {
                return ResourceManager.GetString("DataCheckedFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type must be RAW data.
        /// </summary>
        public static string DataTypeMustBeRAWData {
            get {
                return ResourceManager.GetString("DataTypeMustBeRAWData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datetime format.
        /// </summary>
        public static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default account cannot be edited.
        /// </summary>
        public static string DefaultAccountEdited {
            get {
                return ResourceManager.GetString("DefaultAccountEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user failed.
        /// </summary>
        public static string DeleteAccountFailed {
            get {
                return ResourceManager.GetString("DeleteAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user successfully.
        /// </summary>
        public static string DeleteAccountSuccess {
            get {
                return ResourceManager.GetString("DeleteAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error from NN file.
        /// </summary>
        public static string DetectError {
            get {
                return ResourceManager.GetString("DetectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit the application?.
        /// </summary>
        public static string DoYouWantExitApplication {
            get {
                return ResourceManager.GetString("DoYouWantExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        public static string DoYouWantToContinue {
            get {
                return ResourceManager.GetString("DoYouWantToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to replace existing template?.
        /// </summary>
        public static string DoYouWantToReplaceExistingTemplate {
            get {
                return ResourceManager.GetString("DoYouWantToReplaceExistingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop the system?.
        /// </summary>
        public static string DoYouWantToStopTheSystem {
            get {
                return ResourceManager.GetString("DoYouWantToStopTheSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found NN duplicate datas in database base base on .
        /// </summary>
        public static string DuplicateDataMessage {
            get {
                return ResourceManager.GetString("DuplicateDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user failed.
        /// </summary>
        public static string EditAccountFailed {
            get {
                return ResourceManager.GetString("EditAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user successfully.
        /// </summary>
        public static string EditAccountSuccess {
            get {
                return ResourceManager.GetString("EditAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End index.
        /// </summary>
        public static string EndIndex {
            get {
                return ResourceManager.GetString("EndIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportLog {
            get {
                return ResourceManager.GetString("ExportLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED.
        /// </summary>
        public static string FailedUpperCase {
            get {
                return ResourceManager.GetString("FailedUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data sent to printer when verification failed.
        /// </summary>
        public static string FailureDataSentToPrinter {
            get {
                return ResourceManager.GetString("FailureDataSentToPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullnameColum {
            get {
                return ResourceManager.GetString("FullnameColum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General info.
        /// </summary>
        public static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gennerate.
        /// </summary>
        public static string Gennerate {
            get {
                return ResourceManager.GetString("Gennerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to page.
        /// </summary>
        public static string GoToPage {
            get {
                return ResourceManager.GetString("GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle.
        /// </summary>
        public static string Handle {
            get {
                return ResourceManager.GetString("Handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle error.
        /// </summary>
        public static string HandleError {
            get {
                return ResourceManager.GetString("HandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image export.
        /// </summary>
        public static string ImageExport {
            get {
                return ResourceManager.GetString("ImageExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database path.
        /// </summary>
        public static string ImportDatabase {
            get {
                return ResourceManager.GetString("ImportDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infomation details.
        /// </summary>
        public static string InfomationDetails {
            get {
                return ResourceManager.GetString("InfomationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job details.
        /// </summary>
        public static string JobDetails {
            get {
                return ResourceManager.GetString("JobDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job format.
        /// </summary>
        public static string JobFormat {
            get {
                return ResourceManager.GetString("JobFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job name.
        /// </summary>
        public static string JobList {
            get {
                return ResourceManager.GetString("JobList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job status.
        /// </summary>
        public static string JobStatus {
            get {
                return ResourceManager.GetString("JobStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job system.
        /// </summary>
        public static string JobSystem {
            get {
                return ResourceManager.GetString("JobSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job type.
        /// </summary>
        public static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of field.
        /// </summary>
        public static string ListOfField {
            get {
                return ResourceManager.GetString("ListOfField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading . . ..
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout successfully.
        /// </summary>
        public static string LogoutSuccessfully {
            get {
                return ResourceManager.GetString("LogoutSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor feature is not enabled!.
        /// </summary>
        public static string MonitorFeatureIsNotEnabled {
            get {
                return ResourceManager.GetString("MonitorFeatureIsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New job creation failed!.
        /// </summary>
        public static string NewJobCreationFailed {
            get {
                return ResourceManager.GetString("NewJobCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newly created.
        /// </summary>
        public static string NewLyCreated {
            get {
                return ResourceManager.GetString("NewLyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version.
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No read ouput string.
        /// </summary>
        public static string NoReadOuputString {
            get {
                return ResourceManager.GetString("NoReadOuputString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes: please named object on ISCamera is Object_&lt;n&gt; with n = (1,...5).
        /// </summary>
        public static string NotesForSettingCam {
            get {
                return ResourceManager.GetString("NotesForSettingCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not load database.
        /// </summary>
        public static string NotLoadDatabase {
            get {
                return ResourceManager.GetString("NotLoadDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of printed code.
        /// </summary>
        public static string NumberOfCodesPrinted {
            get {
                return ResourceManager.GetString("NumberOfCodesPrinted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of failed code.
        /// </summary>
        public static string NumberOfFailedCodes {
            get {
                return ResourceManager.GetString("NumberOfFailedCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of mark sensor.
        /// </summary>
        public static string NumberOfMarkSensor {
            get {
                return ResourceManager.GetString("NumberOfMarkSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of valid code.
        /// </summary>
        public static string NumberOfValidCodes {
            get {
                return ResourceManager.GetString("NumberOfValidCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of verified code.
        /// </summary>
        public static string NumberOfVerifiedCode {
            get {
                return ResourceManager.GetString("NumberOfVerifiedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Version.
        /// </summary>
        public static string OldVersion {
            get {
                return ResourceManager.GetString("OldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On production.
        /// </summary>
        public static string OnProduction {
            get {
                return ResourceManager.GetString("OnProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output signal.
        /// </summary>
        public static string OutputSignal {
            get {
                return ResourceManager.GetString("OutputSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSED.
        /// </summary>
        public static string PassedUpperCase {
            get {
                return ResourceManager.GetString("PassedUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password at least 6 character.
        /// </summary>
        public static string PasswordAtLeast6Character {
            get {
                return ResourceManager.GetString("PasswordAtLeast6Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordColumn {
            get {
                return ResourceManager.GetString("PasswordColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not match.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Per {
            get {
                return ResourceManager.GetString("Per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check.
        /// </summary>
        public static string PleaseCheck {
            get {
                return ResourceManager.GetString("PleaseCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the camera connection!.
        /// </summary>
        public static string PleaseCheckTheCameraConnection {
            get {
                return ResourceManager.GetString("PleaseCheckTheCameraConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the database connection!.
        /// </summary>
        public static string PleaseCheckTheDatabaseConnection {
            get {
                return ResourceManager.GetString("PleaseCheckTheDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the printer connection!.
        /// </summary>
        public static string PleaseCheckThePrinterConnection {
            get {
                return ResourceManager.GetString("PleaseCheckThePrinterConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the template!.
        /// </summary>
        public static string PleaseCheckTheTemplate {
            get {
                return ResourceManager.GetString("PleaseCheckTheTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the USB key! Application will close after 60 seconds..
        /// </summary>
        public static string PleaseCheckTheUSBKey {
            get {
                return ResourceManager.GetString("PleaseCheckTheUSBKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a job or create a new one..
        /// </summary>
        public static string PleaseChooseAJobOrCreateANewOne {
            get {
                return ResourceManager.GetString("PleaseChooseAJobOrCreateANewOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the static text.
        /// </summary>
        public static string PleaseEnterTheStaticText {
            get {
                return ResourceManager.GetString("PleaseEnterTheStaticText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input job name.
        /// </summary>
        public static string PleaseInputJobName {
            get {
                return ResourceManager.GetString("PleaseInputJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input template name!.
        /// </summary>
        public static string PleaseInputTemplateName {
            get {
                return ResourceManager.GetString("PleaseInputTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please! Save the work you just entered!.
        /// </summary>
        public static string PleaseSaveTheWorkYouJustEntered {
            get {
                return ResourceManager.GetString("PleaseSaveTheWorkYouJustEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select database path!.
        /// </summary>
        public static string PleaseSelectDatabasePath {
            get {
                return ResourceManager.GetString("PleaseSelectDatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select POD format!.
        /// </summary>
        public static string PleaseSelectPODFormat {
            get {
                return ResourceManager.GetString("PleaseSelectPODFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the database file first!.
        /// </summary>
        public static string PleaseSelectTheDatabaseFileFirst {
            get {
                return ResourceManager.GetString("PleaseSelectTheDatabaseFileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a job for the system.
        /// </summary>
        public static string PleaseSeletedJobForTheSystem {
            get {
                return ResourceManager.GetString("PleaseSeletedJobForTheSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please stop the system before closing the application?.
        /// </summary>
        public static string PleaseStopTheSystemBeforeClosingTheApplication {
            get {
                return ResourceManager.GetString("PleaseStopTheSystemBeforeClosingTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait . . ..
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature requires an app restart to take effect!.
        /// </summary>
        public static string PODChangedWarning {
            get {
                return ResourceManager.GetString("PODChangedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POD feature is not enabled!.
        /// </summary>
        public static string PODFeatureIsNotEnabled {
            get {
                return ResourceManager.GetString("PODFeatureIsNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data compare format.
        /// </summary>
        public static string PODFormat {
            get {
                return ResourceManager.GetString("PODFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of fields from the database.
        /// </summary>
        public static string PODList {
            get {
                return ResourceManager.GetString("PODList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POD mode must be &quot;Print all&quot;.
        /// </summary>
        public static string PODModeMustBePrintAll {
            get {
                return ResourceManager.GetString("PODModeMustBePrintAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POD mode must be &quot;Print last&quot;.
        /// </summary>
        public static string PODModeMustBePrintLast {
            get {
                return ResourceManager.GetString("PODModeMustBePrintLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POD Protocol.
        /// </summary>
        public static string PODProtocol {
            get {
                return ResourceManager.GetString("PODProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview comparison data.
        /// </summary>
        public static string PreviewComparisonData {
            get {
                return ResourceManager.GetString("PreviewComparisonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database preview.
        /// </summary>
        public static string previewdatabase {
            get {
                return ResourceManager.GetString("previewdatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed code.
        /// </summary>
        public static string PrintedCode {
            get {
                return ResourceManager.GetString("PrintedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed response.
        /// </summary>
        public static string PrintedResponse {
            get {
                return ResourceManager.GetString("PrintedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        public static string Printer {
            get {
                return ResourceManager.GetString("Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer disconnected.
        /// </summary>
        public static string PrinterDisconnected {
            get {
                return ResourceManager.GetString("PrinterDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer not support Http Request, please disable &quot;Check All Printer Setting&quot; in setting tab.
        /// </summary>
        public static string PrinterNotSupportHttpRequest {
            get {
                return ResourceManager.GetString("PrinterNotSupportHttpRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer remote port.
        /// </summary>
        public static string PrinterRemotePort {
            get {
                return ResourceManager.GetString("PrinterRemotePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer series.
        /// </summary>
        public static string PrinterSeries {
            get {
                return ResourceManager.GetString("PrinterSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer settings.
        /// </summary>
        public static string PrinterSettings {
            get {
                return ResourceManager.GetString("PrinterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print field.
        /// </summary>
        public static string PrintField {
            get {
                return ResourceManager.GetString("PrintField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing time.
        /// </summary>
        public static string ProcessingTime {
            get {
                return ResourceManager.GetString("ProcessingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program history.
        /// </summary>
        public static string ProgramHistory {
            get {
                return ResourceManager.GetString("ProgramHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string ProgramHistoryFrmMain {
            get {
                return ResourceManager.GetString("ProgramHistoryFrmMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release note.
        /// </summary>
        public static string ReleaseNote {
            get {
                return ResourceManager.GetString("ReleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember password.
        /// </summary>
        public static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprint.
        /// </summary>
        public static string RePrint {
            get {
                return ResourceManager.GetString("RePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reprint?.
        /// </summary>
        public static string ReprintConfirm {
            get {
                return ResourceManager.GetString("ReprintConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-print error! Please restart the software.
        /// </summary>
        public static string ReprintError {
            get {
                return ResourceManager.GetString("ReprintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response content.
        /// </summary>
        public static string ResponseContent {
            get {
                return ResourceManager.GetString("ResponseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response POD Command feature is not enable!.
        /// </summary>
        public static string ResponsePODCommandFeatureIsNotEnable {
            get {
                return ResourceManager.GetString("ResponsePODCommandFeatureIsNotEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response POD data feature is not enable!.
        /// </summary>
        public static string ResponsePODDataFeatureIsNotEnable {
            get {
                return ResourceManager.GetString("ResponsePODDataFeatureIsNotEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result file.
        /// </summary>
        public static string ResultFile {
            get {
                return ResourceManager.GetString("ResultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype password.
        /// </summary>
        public static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string RoleColumn {
            get {
                return ResourceManager.GetString("RoleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R series.
        /// </summary>
        public static string RSeries {
            get {
                return ResourceManager.GetString("RSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification field format.
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected fields.
        /// </summary>
        public static string SelectedField {
            get {
                return ResourceManager.GetString("SelectedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select job.
        /// </summary>
        public static string SelectJob {
            get {
                return ResourceManager.GetString("SelectJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select print field.
        /// </summary>
        public static string SelectPrintField {
            get {
                return ResourceManager.GetString("SelectPrintField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleted job info.
        /// </summary>
        public static string SeletedJobInfo {
            get {
                return ResourceManager.GetString("SeletedJobInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send data method for Verify and print mode.
        /// </summary>
        public static string SendDataMethod {
            get {
                return ResourceManager.GetString("SendDataMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor controller.
        /// </summary>
        public static string SensorController {
            get {
                return ResourceManager.GetString("SensorController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent data.
        /// </summary>
        public static string SentData {
            get {
                return ResourceManager.GetString("SentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some activation parameters are missing! Please check again!.
        /// </summary>
        public static string SomeActivationParametersAreMissing {
            get {
                return ResourceManager.GetString("SomeActivationParametersAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some parameters are missing! Please check again!.
        /// </summary>
        public static string SomeParametersAreMissing {
            get {
                return ResourceManager.GetString("SomeParametersAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some print parameters are missing! Please check again!.
        /// </summary>
        public static string SomePrintParametersAreMissing {
            get {
                return ResourceManager.GetString("SomePrintParametersAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start index.
        /// </summary>
        public static string StartIndex {
            get {
                return ResourceManager.GetString("StartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static text.
        /// </summary>
        public static string StaticText {
            get {
                return ResourceManager.GetString("StaticText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusCode {
            get {
                return ResourceManager.GetString("StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete condition.
        /// </summary>
        public static string StopCondition {
            get {
                return ResourceManager.GetString("StopCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful new job creation! Start the process?.
        /// </summary>
        public static string SuccessfulNewJobCreationStartTheProcess {
            get {
                return ResourceManager.GetString("SuccessfulNewJobCreationStartTheProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support for camera.
        /// </summary>
        public static string SupportForCamera {
            get {
                return ResourceManager.GetString("SupportForCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch user.
        /// </summary>
        public static string SwitchUser {
            get {
                return ResourceManager.GetString("SwitchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System settings.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template print.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name.
        /// </summary>
        public static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text field content.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is empty.
        /// </summary>
        public static string TextboxEmpty {
            get {
                return ResourceManager.GetString("TextboxEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image export function will affect the performance of the system!.
        /// </summary>
        public static string TheImageExportFunction {
            get {
                return ResourceManager.GetString("TheImageExportFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The printer is in an abnormal state, please check again!.
        /// </summary>
        public static string ThePrinterIsInAnAbnormalStatePleaseCheckAgain {
            get {
                return ResourceManager.GetString("ThePrinterIsInAnAbnormalStatePleaseCheckAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one action selected!.
        /// </summary>
        public static string ThereMustBeAtLeastOneActionSelected {
            get {
                return ResourceManager.GetString("ThereMustBeAtLeastOneActionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total checked.
        /// </summary>
        public static string TotalChecked {
            get {
                return ResourceManager.GetString("TotalChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total code of the job.
        /// </summary>
        public static string TotalCodeOfTheJob {
            get {
                return ResourceManager.GetString("TotalCodeOfTheJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of codes in the database.
        /// </summary>
        public static string TotalNumberOfCodeInTheDatabase {
            get {
                return ResourceManager.GetString("TotalNumberOfCodeInTheDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total passed.
        /// </summary>
        public static string TotalPassed {
            get {
                return ResourceManager.GetString("TotalPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        public static string Totals {
            get {
                return ResourceManager.GetString("Totals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        public static string TotalsPrint {
            get {
                return ResourceManager.GetString("TotalsPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access NN file.
        /// </summary>
        public static string UnableToAccess {
            get {
                return ResourceManager.GetString("UnableToAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        public static string Unfinished {
            get {
                return ResourceManager.GetString("Unfinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UsernameColumn {
            get {
                return ResourceManager.GetString("UsernameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exist.
        /// </summary>
        public static string UsernameExist {
            get {
                return ResourceManager.GetString("UsernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name don&apos;t exist.
        /// </summary>
        public static string UsernameNoExist {
            get {
                return ResourceManager.GetString("UsernameNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password cannot be left blank!.
        /// </summary>
        public static string UsernameOrPasswordCannotBeLeftBlank {
            get {
                return ResourceManager.GetString("UsernameOrPasswordCannotBeLeftBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect!.
        /// </summary>
        public static string UsernameOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User stopped the system.
        /// </summary>
        public static string UserStoppedTheSystem {
            get {
                return ResourceManager.GetString("UserStoppedTheSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify and print.
        /// </summary>
        public static string VerifyAndPrint {
            get {
                return ResourceManager.GetString("VerifyAndPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification progress.
        /// </summary>
        public static string VerifyProgress {
            get {
                return ResourceManager.GetString("VerifyProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View log.
        /// </summary>
        public static string ViewLog {
            get {
                return ResourceManager.GetString("ViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to perform this action.
        /// </summary>
        public static string YouDoNotHavePermission {
            get {
                return ResourceManager.GetString("YouDoNotHavePermission", resourceCulture);
            }
        }
    }
}
